import type { Metadata } from 'next'

import '@/styles/globals.css'
import '@/styles/utilities.css'
import Provider from './provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={"bg-light dark:bg-dark text-dark dark:text-light font-base duration-300"}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
